### ISSUE TITLE
missing value handling question

### ISSUE THREAD

**Issue by pavel-shliaha** [Vitek-Lab/MSstatsTMT#10]
Some of the values are missing in TMT experiments and are represented by NA after processing using PD. I believe that in my applications, the reason the values are missing is that they are genuinely 0 (meaning ni signal is present in the channel).  MSstatsTMT imputes these values, since 0s are not allowed in protein summarization and statistical tests.

Would it, however, not be better to multiply all the values by a parge number (say 1e5)  and then assign missing values a value of smth like 10?

**Comment by huang704** [comment]
Do you mean the channel is empty and has no samples? If so, you can label the channel as "Empty" in the annotation file and MSstatsTMT will not impute the values

**Comment by pavel-shliaha** [comment]
No, the channel is not empty (there is some labelling material there), but the value for a particular channel for a particular PSM is NA. E.g. imagine I have a 4plex TMT

126-  NA
127 - NA
128 - 1e3
129 - 1e3

As far as I understand MSstatsTMT will do one of two things:

1. impute the value, which would be a mistake, since NA (returned by PD), in this case, is actually a true NA, meaning no signal is observed
2. use minimum value to impute the missing value for each peptide precursor ion

I would like to use smth like option 2, but the minimal value is a bad approach. since it would assign NAs 1e3, wouldn't it? Making the 4plex

126-  1e3
127 - 1e3
128 - 1e3
129 - 1e3

So my suggestion is to

1. multiply all values by 1e3
2 assign 10 to all NA

making the quantitation data presented into

126-  10
127 - 10
128 - 1e6
129 - 1e6

would this be acceptable, or do you see a problem with this approach?

**Comment by huang704** [comment]
You can ask MSstatsTMT not to impute the NA values. The idea is to assign NA with 0 and make MBimpute of proteinSummarization()  FALSE. The following code can be used to do it.

library(MSstatsTMT)
library(tidyr)
library(dplyr)

annotation <- input.pd  %>% select(Mixture, TechRepMixture, Run, Channel, Condition, BioReplicate) %>% 
  unique()

wide.input <- input.pd  %>% select(ProteinName, PeptideSequence, Charge, PSM, Run, Channel, Intensity) %>% 
  spread(Channel, Intensity) %>% 
  gather(Channel, Intensity, -ProteinName, -PeptideSequence, -Charge, -PSM, -Run) %>% 
  **mutate(Intensity = ifelse(is.na(Intensity), 0, Intensity))**

new.required.input <- full_join(wide.input, annotation)

processed.quant <- proteinSummarization(new.required.input,
                                        method = "msstats", # same as default
                                        global_norm=TRUE, # global peptide normalization between channels
                                        reference_norm=TRUE, # local protein normalization based on refernce channels
                                        **MBimpute = FALSE, # not impute values
                                        maxQuantileforCensored = NULL,**
                                        remove_norm_channel = TRUE, # remove norm channels
                                        remove_empty_channel = TRUE # remove empty channels
)
