### ISSUE TITLE
Error when using TMP for protein summarization.

### ISSUE THREAD

**Issue by weixiandeng** [Vitek-Lab/MSstatsTMT#2]
Hi,
I've been playing with MSstatsTMT for a while, I'm using MaxQuant as search tool, but when I run protein.summarization function with method='MedianPolish' it reports following error: Error in inds_combine(.vars, ind_list) : Position must be between 0 and n.
This error only occurs on MedianPolish but not the other two.
Hope get some clues from you.

Best,
Weixian

**Comment by sichenghao1992** [comment]
Weixian,

Thanks for posting this. Could you please send me the data for this problem at hao.sic@husky.neu.edu?

Sincerely,
Sicheng

**Comment by weixiandeng** [comment]
When I installed older version, this issue got fixed, but I would send you
my data anyway to see what’s going on there.

Best,
Weixian

**Comment by weixiandeng** [comment]
That's awesome, I'd be happy to try the new version.

Another issue is when I was doing comparison using model Limma, it reported
error like this:
Error in `contrasts<-`(`*tmp*`, value = contr.funs[1 + isOF[nn]]) :
  contrasts can be applied only to factors with 2 or more levels

Do you have any suggestion on this problem?

Best,
Weixian

**Comment by dparrine** [comment]
Hello :)

I'm a newbie in R and I have been trying to use MSstatsTMT, however I am getting the following error after running proteinSummarization:

_(after a long list of sequences like:  YNEAVFSTAR_2_NA_NA...)_

> number of columns of result is not a multiple of vector length (arg 2)Error in dataProcess(sub_data, normalization = FALSE, summaryMethod = "TMP",  : 
>   Please remove duplicate rows in the list above.

I appreciate any help! :)
