### ISSUE TITLE
Support for Fragpipe

### ISSUE THREAD

**Issue by weixiandeng** [Vitek-Lab/MSstatsTMT#23]
Hi Ting,

I'm wondering if you have TMT quant output from Fragpipe supported yet?

Best,
Weixian

**Comment by huang704** [comment]
Hi Weixian,

MSstatsTMT hasn't had a converter for the output from Fragpipe yet. But we used MSstatsTMT to analyze the output from philosopher before. The reanalysis is available in massive.quant: https://massive.ucsd.edu/ProteoSAFe/reanalysis.jsp?task=2d0e2fea50bf4b46b77e9b5772e9d20e. The R script is in the ‘methods’ folder (FTP download -> methods).

Best,
Ting

**Comment by weixiandeng** [comment]
> Hi Weixian,
> 
> MSstatsTMT hasn't had a converter for the output from Fragpipe yet. But we used MSstatsTMT to analyze the output from philosopher before. The reanalysis is available in massive.quant: https://massive.ucsd.edu/ProteoSAFe/reanalysis.jsp?task=2d0e2fea50bf4b46b77e9b5772e9d20e. The R script is in the ‘methods’ folder (FTP download -> methods).
> 
> Best,
> Ting

Thank you for the quick response, it is very helpful.

Weixian
