### ISSUE TITLE
MaxQtoMSstatsTMTFormat function doesn't take correct run identifier from annotation file

### ISSUE THREAD

**Issue by weixiandeng** [Vitek-Lab/MSstatsTMT#3]
Hi MSStatsTMT team,

I noticed that in the newest version of MSStatsTMT, which is 0.99.9, MaxQtoMSstatsTMTFormat function wrongly take the identifier from Mixture column instead of Run column. In this case, when doing groupcomparison, it shows the error which is saying have duplicate identifiers from multiple rows.

Best,
Weixian

**Comment by weixiandeng** [comment]
Hi Ting,

Here's the error:
> test.byproposed.median <-
groupComparisonTMT(quant.byprotein.median,remove_norm_channel=FALSE):

Error: Duplicate identifiers for rows (1197, 1198, 1199, 1200), (99817,
99818, 99819, 99820), (80649, 80650, 80651, 80652), (3129, 3130, 3131,
3132), (53677, 53678, 53679, 53680), (51989, 51990, 51991, 51992),..........

The output from proteinsummarization is like this:
> head(quant.byprotein.medianpolish)
       Run               Protein Abundance   Channel BioReplicate Condition
Mixture
1 Mixture1 A0A087WP63;A0A087WQ44        NA channel.1            1
 no-APEX       1
2 Mixture1 A0A087WP63;A0A087WQ44        NA channel.1           19
 no-APEX       1
3 Mixture1 A0A087WP63;A0A087WQ44        NA channel.1           37
 no-APEX       1
4 Mixture1 A0A087WP63;A0A087WQ44        NA channel.1           55
 no-APEX       1
5 Mixture1 A0A087WP63;A0A087WQ44  13.19828 channel.2            2
 BIC       1
6 Mixture1 A0A087WP63;A0A087WQ44  13.19828 channel.2           20
 BIC       1

and my annotation file is like this:
> head(mq.annotation)
                                               Run   Channel Condition
Mixture
1 2018-11-29-140min-200nl-WD-Wendy-TMT-Fraction1-A channel.1   no-APEX
Mixture1
2 2018-11-29-140min-200nl-WD-Wendy-TMT-Fraction1-A channel.2       BIC
Mixture1
3 2018-11-29-140min-200nl-WD-Wendy-TMT-Fraction1-A channel.3      Norm
Mixture1
4 2018-11-29-140min-200nl-WD-Wendy-TMT-Fraction1-A channel.4      Norm
Mixture1
5 2018-11-29-140min-200nl-WD-Wendy-TMT-Fraction1-A channel.5   no-APEX
Mixture1
6 2018-11-29-140min-200nl-WD-Wendy-TMT-Fraction1-A channel.6   no-APEX
Mixture1
  BioReplicate
1            1
2            2
3            3
4            4
5            5
6            6

The output of format transform function is like this:
> head(input.MQ)
  ProteinName PeptideSequence Charge              PSM   Channel Condition
BioReplicate
1      Q61171     QITVNDLPVGR      2    QITVNDLPVGR_2 channel.1   no-APEX
          1
2      Q9CQN1      NIYYLCAPNR      2     NIYYLCAPNR_2 channel.1   no-APEX
          1
3      P61358       YSVDIPLDK      2      YSVDIPLDK_2 channel.1   no-APEX
          1
4      P11798      VLAGQEYAAK      2     VLAGQEYAAK_2 channel.1   no-APEX
          1
5      Q8BTI8  TAVAPSAVNLADPR      2 TAVAPSAVNLADPR_2 channel.1   no-APEX
          1
6      Q61753     VTADVINAAEK      2    VTADVINAAEK_2 channel.1   no-APEX
          1
       Run Mixture Intensity
1 Mixture1       1   3518.30
2 Mixture1       1    865.25
3 Mixture1       1    987.52
4 Mixture1       1   8453.40
5 Mixture1       1   2017.90
6 Mixture1       1    892.46

So I guess something funny happened with this -MaxQtoMSstatsTMTFormat
function.

It was completely fine when I used these input files in older version, I
noticed you guys changed some names of the function and parameters, here's
the code for new version:

library('MSstatsTMT')
raw.mq<-
read.table("C:/Research/2018-11-29-Wendy-TMT/combined/txt/evidence.txt",sep
= "\t",header = TRUE)
protein.group<-read.table("C:/Research/2018-11-29-Wendy-TMT/combined/txt/proteinGroups.txt",header
= TRUE,sep = "\t")
mq.annotation<-read.table("C:/Research/2018-11-29-Wendy-TMT/combined/txt/MSStatsTMT_annotation.txt",header
= TRUE,sep = "\t")




input.MQ<-MaxQtoMSstatsTMTFormat(evidence = raw.mq, proteinGroups =
protein.group, annotation = mq.annotation, fraction = TRUE,
                                which.proteinid = "Proteins",
                                rmProt_Only.identified.by.site = FALSE,
                                useUniquePeptide = TRUE,
rmPSM_withMissing_withinRun = FALSE,
                                rmPSM_withfewMea_withinRun = FALSE,
rmProtein_with1Feature = FALSE,
                                summaryforMultipleRows = sum)



quant.byprotein.median <- proteinSummarization(input.MQ,
                                                method="Median",
                                                normalization=FALSE)
quant.byprotein.LogSum <- proteinSummarization(input.MQ,
                                                method="LogSum",
                                                normalization=FALSE)
quant.byprotein.medianpolish<-proteinSummarization(input.MQ,
                                                    method="MedianPolish",
                                                    normalization=FALSE)

test.byproposed.median <-
groupComparisonTMT(quant.byprotein.median,remove_norm_channel=FALSE)
test.byproposed.LogSum <-
groupComparisonTMT(quant.byprotein.LogSum,remove_norm_channel=FALSE)
test.byproposed.medianpolish <-
groupComparisonTMT(quant.byprotein.medianpolish,remove_norm_channel=FALSE)

Thank you for your quick response and help!

Best,
Weixian

**Comment by huang704** [comment]
Hi Weixian,

The output from MaxQtoMSstatsTMTFormat seems no problem. I think the error may come from groupComparisonTMT() function. We indeed made some changes to groupComparisonTMT().

If it is possible, could you share the quant.byprotein.median data with us? If it is too large, you can just send the first 2000 rows. We'd like to have a look at the following rows:

**Error: Duplicate identifiers for rows (1197, 1198, 1199, 1200)**

Also, does the error only occur for quant.byprotein.median? Or it happens for quant.byprotein.medianpolish and quant.byprotein.LogSum, too? Now MSstatsTMT provides a new method option called "MSstats" in proteinSummarization(). It can impute missing values. You may want to try it.

Best,
Ting

**Comment by weixiandeng** [comment]
Hi Ting,

It happened on outputs from all three protein summarization methods. 
For instance:
test.byproposed.medianpolish <- groupComparisonTMT(quant.byprotein.medianpolish,remove_norm_channel=FALSE)
Error: Duplicate identifiers for rows (1, 2, 3, 4), (37, 38, 39, 40), (73, 74, 75, 76), (109, 110, 111, 112), (145, 146, 147, 148), (181, 182, 183, 184), (217, 218, 219, 220), (253, 254, 255, 256),

Then here's the quant.byprotein.medianpolish file:

head(quant.byprotein.medianpolish)
       Run               Protein Abundance   Channel BioReplicate Condition
1 Mixture1 A0A087WP63;A0A087WQ44        NA channel.1            1   no-APEX
2 Mixture1 A0A087WP63;A0A087WQ44        NA channel.1           19   no-APEX
3 Mixture1 A0A087WP63;A0A087WQ44        NA channel.1           37   no-APEX
4 Mixture1 A0A087WP63;A0A087WQ44        NA channel.1           55   no-APEX
5 Mixture1 A0A087WP63;A0A087WQ44  13.19828 channel.2            2       BIC
6 Mixture1 A0A087WP63;A0A087WQ44  13.19828 channel.2           20       BIC
  Mixture
1       1
2       1
3       1
4       1
5       1
6       1

Best,

Weixian

**Comment by huang704** [comment]
I see the problem. There are duplicate rows in the output from proteinSummarization() if ignoring the BioReplicate column. I think there may be some wrong with the annotation file. Could you attach the complete annotation file you use?

We made some changes to groupComparisonTMT() so that it can detect this bug now.

Best,
Ting

**Comment by huang704** [comment]
If I understand it correctly, the data has only one TMT mixture with 4 fractions and two technical replicates. Is that correct?

**Comment by weixiandeng** [comment]
Yes, it is, exactly.

**Comment by weixiandeng** [comment]
The reason why I made such design, is that when I set all of them as one single experiment in MaxQuant and set annotation as all the files are from single mixture, it wouldn't get through the proteinsummarization function, I can't  remember how exactly the error information now.
So I made it as two separate experiments in MaxQuant, and set them as 2 different mixture in MSStats annotation files, and it got through.

**Comment by huang704** [comment]
Okay. Here is the problem. The current version of MSstatsTMT can deal with the data which has either fractionation or technical replicates. For your data with both fractionation and technical replicates, MSstatsTMT doesn't cover. The design with both fractionation and technical replicate will be included in next release of MSstatsTMT.

You may get the testing results from version MSstatsTMT 0.3.5. But they are incorrect. In the version 1.0.0, we made some change to groupComparisonTMT() so it reported this error.

I will send you a dev version MSstatsTMT later, which can work with your data. But it requires more information in the annotation since it has one additional column, called **Fraction**.

**Comment by weixiandeng** [comment]
That's great! Thank you so much. I thought that using 2 mixtures stand for 2 technical replicates would just increase 1 more set of data points for the final group comparison, so I didn't pay much attention to it.

**Comment by weixiandeng** [comment]
Ok, cool. Look forward to see your new version as well. 

Another question about Limma, I tried it in version 0.3.5 it reports following error:

> test.byproposed.medianpolish.limma <- groupComparison.TMT(quant.byprotein.medianpolish,model = 'limma',remove_norm_channel=FALSE)
Error in `contrasts<-`(`*tmp*`, value = contr.funs[1 + isOF[nn]]) : 
  contrasts can be applied only to factors with 2 or more levels

I don't quite understand it.

**Comment by huang704** [comment]
Model "Limma" is for our internal testing.  We have removed it from version 1.0.0. From the error message, it is hard to say the reason. It may be just because we didn't make the condition as factor.

**Comment by weixiandeng** [comment]
Thank you! If you are still interested in sharing newer version, I'd be happy to explore around.

**Comment by huang704** [comment]
Sure, I will send it to you after I finish the testing.

**Comment by weixiandeng** [comment]
Awesome!
