### ISSUE TITLE
.make.contrast.single bug when groups contain the string "Group"

### ISSUE THREAD

**Issue by romanzenka** [Vitek-Lab/MSstatsTMT#30]
I ran into a bizarre issue where MSstatsTMT completely failed to produce output.

I tracked it to this line in `.make.contrast.single`:

```r
group_c <- tempcontrast[gsub("Group", "", temp)]
```

Suggestion: use `"^Group"` in the `gsub` call.

**Comment by mstaniak** [comment]
Does the problem persist in MSstatsTMT v2?

**Comment by mstaniak** [comment]
Looks like it does. @huang704 luckily it's an easy fix.

Thank you for pointing this out @romanzenka
