### ISSUE TITLE
Run column changing to duplicate of Mixture after using PDtoMSstatsTMTFormat()

### ISSUE THREAD

**Issue by EHogan-Research** [Vitek-Lab/MSstatsTMT#38]
After using PDtoMSstatsTMTFormat(), my output dataframe has a duplicate of the mixture name where the run information should be.

My PD dataframe (named peptides):
  PSMs.Workflow.ID PSMs.Peptide.ID Checked Confidence   Identifying.Node PSM.Ambiguity        Annotated.Sequence
1              -22         1902915   False       High    Sequest HT (A2)   Unambiguous  [R].eQLTEGEEIAQEIDGR.[F]
2              -22         1129169   False       High MS Amanda 2.0 (A4)   Unambiguous     [K].gSFSEQGINEFLR.[E]
3              -22         1129152   False       High MS Amanda 2.0 (A4)   Unambiguous   [R].gFAFVTFDDHDSVDk.[I]
4              -22         1129148   False       High MS Amanda 2.0 (A4)   Unambiguous     [R].aVSWTFSEENVIR.[E]
5              -22         3199194   False       High    Sequest HT (A2)   Unambiguous [R].sLGYAYVNFQQPADAER.[A]
6              -22         3199177   False       High    Sequest HT (A2)   Unambiguous   [K].qLEAIDQLHLEYAkR.[A]
                    Modifications Number.of.Protein.Groups Number.of.Proteins Master.Protein.Accessions
1                N-Term(TMT6plex)                        1                  1                    Q9NRY4
2                N-Term(TMT6plex)                        1                  5                  Q15084-2
3 N-Term(TMT6plex); K15(TMT6plex)                        2                  4          P09651-2; P09651
4                N-Term(TMT6plex)                        1                  2                    Q9Y320
5                N-Term(TMT6plex)                        2                  5          Q13310-3; P11940
6 N-Term(TMT6plex); K14(TMT6plex)                        1                  3                    O43707
                              Protein.Accessions Number.of.Missed.Cleavages Charge Delta.Score Delta.Cn Rank Search.Engine.Rank
1                                         Q9NRY4                          0      3      0.3475        0    1                  1
2 Q15084-2; Q15084-5; Q15084-3; Q15084-4; Q15084                          0      3      0.7133        0    1                  1
3             P09651-2; Q32P51; P09651-3; P09651                          0      3      0.6073        0    1                  1
4                               Q9Y320; Q9Y320-2                          0      2      0.7547        0    1                  1
5   P11940-2; Q13310-2; Q13310-3; Q13310; P11940                          0      2      0.6507        0    1                  1
6                     O43707-3; O43707-2; O43707                          1      4      0.6108        0    1                  1
   mz.in.Da MHplus.in.Da Theo.MHplus.in.Da Delta.M.in.ppm Delta.mz.in.Da Activation.Type MS.Order Isolation.Interference.in.Percent
1  682.6784     2046.021          2046.019           0.91        0.00062             CID      MS2                         13.265330
2  571.6313     1712.879          1712.881          -0.73       -0.00042             CID      MS2                         51.300690
3  720.0338     2158.087          2158.086           0.52        0.00038             CID      MS2                          9.272033
4  883.9666     1766.926          1766.927          -0.82       -0.00073             CID      MS2                          0.000000
5 1079.5407     2158.074          2158.077          -1.19       -0.00129             CID      MS2                          0.000000
6  572.0807     2285.301          2285.302          -0.38       -0.00022             CID      MS2                          0.000000
  Average.Reporter.SN Ion.Inject.Time.in.ms RT.in.min First.Scan                                   Spectrum.File File.ID Abundance.126
1                63.0                 3.211   12.7153       8732  20200116_UVPD_SartoriRodriguesM_Fraction_6.raw    F1.6          33.0
2                49.6                 1.174   11.1366       7464 20200116_UVPD_SartoriRodriguesM_Fraction_39.raw   F1.38          77.6
3                33.2                 0.848   11.1594       7481 20200116_UVPD_SartoriRodriguesM_Fraction_39.raw   F1.38          22.4
4                 5.2                 1.181   11.1605       7482 20200116_UVPD_SartoriRodriguesM_Fraction_39.raw   F1.38           5.7
5                 7.1                 1.929    9.2801       5952 20200116_UVPD_SartoriRodriguesM_Fraction_40.raw   F1.39          12.9
6                82.2                 0.525    9.2778       5950 20200116_UVPD_SartoriRodriguesM_Fraction_40.raw   F1.39         149.9
  Abundance.127N Abundance.127C Abundance.128N Abundance.128C Abundance.129N Abundance.129C Abundance.130N Abundance.130C Quan.Info
1          119.5           75.2           96.5           66.5           55.5           45.1           90.8           40.6          
2           93.9           76.8           75.0           69.6           27.1           21.9           25.4           15.3          
3           50.6           27.2           39.2           32.1           28.1           43.5           60.4           38.6          
4            8.9            6.3            6.5            4.8            4.5            5.9            5.0            5.5          
5           13.4            9.4           11.8           11.5            4.8            4.5            2.4            2.1          
6          154.9          104.7          152.3          136.0           39.6           53.9           22.0           22.5          
  Amanda.Score CharmeRT.Combined.Score Search.Space MS.Amanda.Rank Search.Depth XCorr Percolator.q.Value Percolator.PEP
1           NA                      NA            0              0            0  4.00                  0      2.410e-06
2       209.45                  209.45          641              1            1    NA                  0      2.339e-06
3       180.59                  180.59         1082              1            1    NA                  0      1.247e-06
4       163.13                  163.13          648              1            1    NA                  0      1.887e-05
5           NA                      NA            0              0            0  6.07                  0      6.123e-07
6           NA                      NA            0              0            0  4.83                  0      8.321e-06

The annotation dataframe (named annotation_df):
                                             Run Fraction TechRepMixture Channel Condition BioReplicate  Mixture
1 20200116_UVPD_SartoriRodriguesM_Fraction_6.raw        6              1     126   RTT_NPC            1 Mixture1
2 20200116_UVPD_SartoriRodriguesM_Fraction_6.raw        6              1    127N    WT_NPC            2 Mixture1
3 20200116_UVPD_SartoriRodriguesM_Fraction_6.raw        6              1    127C   RTT_NPC            2 Mixture1
4 20200116_UVPD_SartoriRodriguesM_Fraction_6.raw        6              1    128N    WT_NPC            3 Mixture1
5 20200116_UVPD_SartoriRodriguesM_Fraction_6.raw        6              1    128C   RTT_NPC            3 Mixture1
6 20200116_UVPD_SartoriRodriguesM_Fraction_6.raw        6              1    129N    WT_NEU            1 Mixture1

I ran the following command:
TMTpeptides <- PDtoMSstatsTMTFormat(peptides, annotation_df, rmPSM_withMissing_withinRun = TRUE, useNumProteinsColumn = F)

The resulting dataframe:
                 ProteinName             PeptideSequence Charge                           PSM  Mixture TechRepMixture        Run Channel
1 Q9UK76-3; Q9UK76; Q9UK76-2 [-K].mASNIFGTPEENQASWAk.[S]      2 [-K].mASNIFGTPEENQASWAk.[S]_2 Mixture1              1 Mixture1_1     126
2 Q9UK76-3; Q9UK76; Q9UK76-2 [-K].mASNIFGTPEENQASWAk.[S]      2 [-K].mASNIFGTPEENQASWAk.[S]_2 Mixture1              1 Mixture1_1    127C
3 Q9UK76-3; Q9UK76; Q9UK76-2 [-K].mASNIFGTPEENQASWAk.[S]      2 [-K].mASNIFGTPEENQASWAk.[S]_2 Mixture1              1 Mixture1_1    127N
4 Q9UK76-3; Q9UK76; Q9UK76-2 [-K].mASNIFGTPEENQASWAk.[S]      2 [-K].mASNIFGTPEENQASWAk.[S]_2 Mixture1              1 Mixture1_1    128C
5 Q9UK76-3; Q9UK76; Q9UK76-2 [-K].mASNIFGTPEENQASWAk.[S]      2 [-K].mASNIFGTPEENQASWAk.[S]_2 Mixture1              1 Mixture1_1    128N
6 Q9UK76-3; Q9UK76; Q9UK76-2 [-K].mASNIFGTPEENQASWAk.[S]      2 [-K].mASNIFGTPEENQASWAk.[S]_2 Mixture1              1 Mixture1_1    129C
  BioReplicate Condition Intensity
1            1   RTT_NPC      85.2
2            2   RTT_NPC      79.8
3            2    WT_NPC     103.4
4            3   RTT_NPC      71.7
5            3    WT_NPC      71.0
6            1   RTT_NEU      76.6

All of my Run names have been changed to Mixture1_1. Is there an easy way to fix this? Thank you!

**Comment by mstaniak** [comment]
This is intended behavior. Fractions from a mixture and technical replicate are aggregated, and then Mixture+TechRepMixture is treated as Run label.

**Comment by mstaniak** [comment]
Please

**Comment by mstaniak** [comment]
Please let us know if there's more to clarify, otherwise let's close this issue.

**Comment by EHogan-Research** [comment]
Ah, I misunderstood what was happening then. I'll read the documentation again. Thank you!
