### ISSUE TITLE
dataProcess breaks proteinSummarization in TMT analysis (MSstatsTMT 1.0.1)

### ISSUE THREAD

**Issue by fredrious** [Vitek-Lab/MSstatsTMT#4]
https://github.com/Vitek-Lab/MSstatsTMT/blob/a66c093061edc47111fc48392ca216816d6565e6/R/proteinSummarization.functions.R#L68

In line **668** of **MSstats::dataProces**s, a dataframe (_"tempmissingwork")_ is to be generated from parameters with different dimensions. In my data, the _"nameID"_ has a dimension of (12,7) and the "_tempfeatureID_" has a dimension of (1345,4). This makes the following command to break the code:

`tempmissingwork <- data.frame(tempfeatureID, 
              LABEL = "L", GROUP_ORIGINAL = nameID$GROUP_ORIGINAL, 
              SUBJECT_ORIGINAL = nameID$SUBJECT_ORIGINAL, 
              RUN = nameID$RUN, GROUP = nameID$GROUP, 
              SUBJECT = nameID$SUBJECT, SUBJECT_NESTED = nameID$SUBJECT_NESTED, 
              INTENSITY = NA, ABUNDANCE = NA, FRACTION = nameID$FRACTION)`

The _nameID_ is:

 | SUBJECT_ORIGINAL  | GROUP_ORIGINAL | GROUP | SUBJECT | SUBJECT_NESTED | RUN | FRACTION |
  |----------|-----|---|----|------|-------|---|
  | 1.1.126  | mdx | 3 | 1  | 3.1  | 1_126 | 1 |
  | 1.2.126  | mdx | 3 | 11 | 3.21 | 1_126 | 1 |  
  | 1.3.126  | mdx | 3 | 21 | 3.31 | 1_126 | 1 | 
  | 1.4.126  | mdx | 3 | 31 | 3.41 | 1_126 | 1 |
  | 1.5.126  | mdx | 3 | 41 | 3.51 | 1_126 | 1 |
  | 1.6.126  | mdx | 3 | 51 | 3.61 | 1_126 | 1 |
  | 1.7.126  | mdx | 3 | 61 | 3.71 | 1_126 | 1 |
  | 1.8.126  | mdx | 3 | 71 | 3.81 | 1_126 | 1 |
  | 1.9.126  | mdx | 3 | 81 | 3.91 | 1_126 | 1 |
  | 1.10.126 | mdx | 3 | 91 | 3.101| 1_126 | 1 |
  | 1.11.126 | mdx | 3 | 101| 3.111| 1_126 | 1 |
  | 1.12.126 | mdx | 3 | 111| 3.121| 1_126 | 1 |

and the _tempfeatureID_:

  | PROTEIN  |    PEPTIDE                        |  TRANSITION |  FEATURE                             |
  |----------|-----|---|----|
  | Q6PGF7   |    [R].eGSGTGEEGk.[Q]_2           |  NA_NA      |  [R].eGSGTGEEGk.[Q]_2_NA_NA          |
  | Q9CZ13   |    [R].NALVSHLDGTTPVcEDIGR.[S]_3  |  NA_NA      |  [R].NALVSHLDGTTPVcEDIGR.[S]_3_NA_NA |
  | Q7TSK3   |    [R].dVNDHAPR.[F]_3             |  NA_NA      |  [R].dVNDHAPR.[F]_3_NA_NA            |
  | Q8VE33   |    [R].LNLGEEVPVIIHR.[D]_3        |  NA_NA      |  [R].LNLGEEVPVIIHR.[D]_3_NA_NA       |
  |...|...|...|...|

The complete dataset consists of thousands of proteins, however I tested the MSstatsTMT workflow with a subset of 20 and 50 proteins, but the code still breaks at this point.

I assume the code should be something like this:
`tempmissingwork <- merge(tempfeatureID, data.frame( 
           LABEL = "L", GROUP_ORIGINAL = nameID$GROUP_ORIGINAL, 
           SUBJECT_ORIGINAL = nameID$SUBJECT_ORIGINAL, 
           RUN = nameID$RUN, GROUP = nameID$GROUP, 
           SUBJECT = nameID$SUBJECT, SUBJECT_NESTED = nameID$SUBJECT_NESTED, 
           INTENSITY = NA, ABUNDANCE = NA, FRACTION = nameID$FRACTION))`

**Comment by huang704** [comment]
Sorry, I didn't fully understand your question. MSstatsTMT calls the dataProcess() function from MSstats on each TMT run individually. Do you want to generate the input data to dataProcess() by yourself, which is tempmissingwork? If so, your final guess seems correct. You need to merge tempfeatureID and the annotation info (nameID) by Run to get a long format input.
