### ISSUE TITLE
unclear columns in annotation.pd

### ISSUE THREAD

**Issue by pavel-shliaha** [Vitek-Lab/MSstatsTMT#5]
I am trying to load some data into MSstatsTMT and the meaning of the columns in annotation.pd is very unclear to me (I use both TMT and bioinformatics software regularly).

"Mixture : Mixture of samples labeled with different TMT reagents, which can be analyzed in a
single mass spectrometry experiment. If the channal doesn’t have sample, please add ‘Empty’
under Condition."

TMT is always a mixture of samples, what is this column supposed to convey?

"TechRepMixture : Technical replicate of one mixture. One mixture may have multiple technical replicates. For example, if ‘TechRepMixture’ = 1, 2 are the two technical replicates of
one mixture, then they should match with same ‘Mixture’ value."

"Fraction : Fraction ID. One technical replicate of one mixture may be fractionated into multiple fractions to increase the analytical depth. Then one technical replicate of one mixture
should correspond to multuple fractions. For example, if ‘Fraction’ = 1, 2, 3 are three fractions of the first technical replicate of one TMT mixture of biological subjects, then they
should have same ‘TechRepMixture’ and ‘Mixture’ value"

I would suggest you describe a specific example to make it clear. E.g. I have a 16plex experiment, with 16 samples in 4 conditions:

condition 1: channels 1:4
condition 2: channels 5:8
condition 3: channels 9:12
condition 4: channels 13:16

after the samples are labelled and pooled, the pool is fractionated into 4 fractions, each of them is run individually and produces a separate raw file, the raw files are co-analysed (specified as fractions in PD) to produce a single PSM.csv. What should the columns of annotation.pd say?

**Comment by huang704** [comment]
For the example design you gave, the annotation file should be:

- Mixture: can be "mixture1" or other single value since there is only one mixture of 16 samples. 
- TechRepMixture: can be "1" or other single value since there is no technical replicate run of the mixture
- Fraction: should be "1", "2", "3", "4" since there are 4 fractions.
- Run: MS run ID. It should be the same as Spectrum.File info in PSM.csv, corresponding with the Fraction ID.

**Comment by huang704** [comment]
The error is because of the difference in the channel intensity columns. If you check the example data raw.pd in MSstatsTMT, the channel intensity columns are like: Abundance..126, Abundance..127N and so on. Could you try to change the channel column names in your PSM table to  "Abundance..126", "Abundance..127N", "Abundance..127C"?

**Comment by pavel-shliaha** [comment]
The vignette provides a different case:

http://127.0.0.1:14236/library/MSstatsTMT/doc/MSstatsTMT.html

it is shown that PD input should have quantitation columns marked with"abundance", while annotation.pd has the columns marked as simply "126" and so on

![msstats](https://user-images.githubusercontent.com/1895805/67977102-c73d1200-fbed-11e9-8c81-f152a6595c64.JPG)

**Comment by huang704** [comment]
Could you reinstall MSstatsTMT 1.4.1 from github again?  It should work now. The error is mainly because you use a new version of PD and MSstatsTMT 1.3 didn't cover it. I have updated PD converter to work with the new PD output.

**Comment by pavel-shliaha** [comment]
Could you please provide the code to install from gihub? I tried reinstalling from bioconductor but it did not help

**Comment by huang704** [comment]
install.packages("devtools")
library(devtools)
install_github("MSstatsTMT/MSstatsTMT")

It may remind you some dependent packages are missing. Then you just need to install them according to the message.

If you are not hurry, I'll push the change to Bioconductor today. So you can reinstall the latest package from Bioconductor next Monday.

**Comment by huang704** [comment]
MSstatsTMT in bioconductor has been updated to 1.4.1, which should work for your dataset. You can reinstall MSstatsTMT from bioconductor to try.
