### ISSUE TITLE
Error in proteinSummarization - possible annotation issue?

### ISSUE THREAD

**Issue by caitsimop** [Vitek-Lab/MSstatsTMT#52]
I'm running into a weird error when using the `"msstats"` method in `proteinSummarization()`. I believe this may have to do with my annotation file as I am not using a converter and doing this manually. 

Here is an example of the error I encounter: 
```
quant.msstats <- proteinSummarization(msstatsinput,
+                                       method="msstats", 
+                                       global_norm=TRUE,
+                                       reference_norm=TRUE,
+                                       remove_norm_channel = TRUE,
+                                       remove_empty_channel = TRUE)
INFO  [2021-12-08 16:14:23] ** MSstatsTMT - proteinSummarization function
INFO  [2021-12-08 16:15:09] Summarizing for Run : TMT_V46_P1E ( 1  of  194 )
  |=                                                  |   2%Aggregate function missing, defaulting to 'length'
<simpleError in .Primitive("length")(newABUNDANCE, keep = TRUE): 2 arguments passed to 'length' which requires 1>
Error in merge.data.table(input[, colnames(input) != "newABUNDANCE", with = FALSE],  : 
  Elements listed in `by` must be valid column names in x and y
In addition: Warning message:
In merge.data.table(input[, colnames(input) != "newABUNDANCE", with = FALSE],  :
  You are trying to join data.tables where 'y' argument is 0 columns data.table.
```

I'm hoping someone can point me in the right direction where I'm going wrong. Thanks!

**Comment by mstaniak** [comment]
Hi,
thanks for reporting the issue, can you please show us your annotation file?

**Comment by caitsimop** [comment]
Hi @mstaniak,
Would it be ok for me to email you the file?

**Comment by mstaniak** [comment]
sure, e-mail is fine

**Comment by caitsimop** [comment]
I was able to censor the annotation file to upload here in case it also can help someone else.
See below. 
Thanks!
[annotation_censored.txt](https://github.com/Vitek-Lab/MSstatsTMT/files/7686436/annotation_censored.txt)

**Comment by mstaniak** [comment]
How many conditions are there?

**Comment by caitsimop** [comment]
We have quite a few conditions. I realized in censoring the data I inadvertently added some conditions, but in total we have 318 including the "Norm".

**Comment by caitsimop** [comment]
There are 6 biological replicates (there should be 7 total IDs, one is QC and doesn't have any conditions). 

It is not a time course experiment. We will be comparing treatments/groups.

**Comment by mstaniak** [comment]
Can you provide a very small subset of data to reproduce the problem? One anonymized protein that throws this error is enough. Thanks in advance, unfortunately, this annotation is not enough to locate the issue.

**Comment by caitsimop** [comment]
Hi!

Here is a small subset of [censored data: ](https://github.com/Vitek-Lab/MSstatsTMT/files/7715259/troubleshoot_prot.txt):

Thanks!

**Comment by mstaniak** [comment]
Thanks. This particular error is due to underscores in peptide sequence column. There shouldn't be any

**Comment by caitsimop** [comment]
Thank you! 

I ended up removing the following from the peptide sequences and I avoid the error: ` _ - > <`

I'm now encountering the following warning: 

```
Warning messages:
1: In survreg.fit(X, Y, weights, offset, init = init, controlvals = control,  :
  Ran out of iterations and did not converge
```

Is it possible to manually set more iterations for this function?

**Comment by mstaniak** [comment]
Currently not, don't worry about this warning, it's not a real problem. I might add a parameter for this in a future version, but it's not important. Did the original problem disappear? Your example does throw an error for me

**Comment by caitsimop** [comment]
Thanks, mstaniak.

Yes, I no longer encountered the error once I removed any of these characters from the peptide sequences: `_ - > <`.
