### ISSUE TITLE
old version of MSstatsTMT

### ISSUE THREAD

**Issue by komwoort** [Vitek-Lab/MSstatsTMT#53]
Hello MSstats team

first of all, I really appreciate for this amazing package.
I have one quick question about MSstatsTMT.
As I am not familiar with R code or package, it might be a basic question. 
Where can I find older version of MsstatsTMT package??
I would like to match the result with previous one which was run before update ( I run first data on about May 2020)

I appreciate for your help.

Sincerely,

**Comment by huang704** [comment]
Which old version of MSstatsTMT did you use? There are two versions of MSstatsTMT released in May 2020: https://bioconductor.org/packages/3.11/bioc/src/contrib/Archive/MSstatsTMT/

To install a specified version of a bioconductor package, you can look at the information in https://stackoverflow.com/questions/49487171/r-how-to-install-a-specified-version-of-a-bioconductor-package.
