### ISSUE TITLE
Fragpipe 

### ISSUE THREAD

**Issue by ohovey5** [Vitek-Lab/MSstatsTMT#57]
Fragpipe has been giving significantly better TMT data than Maxquant for us. What is the best way to import Fragpipe data into MSstatsTMT and MSstatsTMTPTM?

**Comment by tobiasko** [comment]
Hi @devonjkohler ,

I am also trying to import `msstats.csv` written by Philosopher 4.8.1 into MStstatsTMT, see [FragPipe issue 510](https://github.com/Nesvilab/FragPipe/issues/510). The FragPipe team told me this currently not possible, but could not really explain why.

Could you maybe comment on why your `MSstatsTMT::PhilosophertoMSstatsTMTFormat()` function fails to generate complete input data?

Thanks,
Tobi

**Comment by fcyu** [comment]
Hi Tobi @tobiasko ,

The reasons are simple: there were bugs in the released Philosopher. You can try our pre-released version mentioned in https://github.com/Nesvilab/FragPipe/issues/510

In case you are interested what changes have been made, I did a little search on the https://github.com/Nesvilab/philosopher and found the following commits:

https://github.com/Nesvilab/philosopher/commit/ed401dbb57d2f47eb4e14a2ede07d1b93f891688
https://github.com/Nesvilab/philosopher/commit/95b8e3138ee3e00e9c988283580afecd94095e24
https://github.com/Nesvilab/philosopher/commit/f55933ea4417c6909261f03ce2c4e1a1d55b7cc6
https://github.com/Nesvilab/philosopher/commit/9b37116ec0aea83d458f30eba6e3d9db091e71d6

Best,

Fengchao

**Comment by devonjkohler** [comment]
Thanks Fengchao,

This is an old issue and the converter has been added (and tested with the new Fragpipe output). I am closing this issue for now.

Devon

**Comment by tobiasko** [comment]
@fcyu THX! Looks like massive code changes and not only restricted to `msstats.csv`.

**Comment by fcyu** [comment]
Hi @tobiasko ,

Kind of. As far as I can remember, we 1) fixed bugs in generating `msstats.csv` (some columns/column names were incorrect); 2) made Philosopher generate a "combined" `msstats.csv`; 3) made FragPipe generate `MSstatsTMT_annotation.csv` file (code not included in the Philosopher repository, but in FragPipe repository).

Best,

Fengchao
