### ISSUE TITLE
Suppression of ratios during proteinSummarization

### ISSUE THREAD

**Issue by pavel-shliaha** [Vitek-Lab/MSstatsTMT#6]
I am performing an IP-MS/MS with TMTPro. There are 4 cell lines

1. channels 1:4 (126:128N). No proteins are tagged.
2. channels 5:8 (128C:130N). Q9H9L4 is flag tagged.
3. channels 9:12 (130C:132N).  Q9P2N6 is flag tagged.
4. channels 13:16 (132C:134N). Q9H7Z6 is flag tagged.

Ip is performed on all cell lines with anti-FLAG beads.

I ran the samples in MS3 SPS mode and the quantitation performed as expected: Q9H9L4 is almost exclusively present in 128C:130N,   Q9P2N6 in 130C:132N and Q9H7Z6 in 132C:134N channels. This is seen on level of peptides after PDtoMSstatsTMTFormat conversion:

![baits](https://user-images.githubusercontent.com/1895805/76375439-bdff4700-633d-11ea-9a5b-abad3a501e9f.png)

The black lines represent individual PSMs, the red line is the average of all PSMs as computed by ggplot2. 

However, when the quantitation is rolled up to protein level, the ratios become extremely suppressed and now the baits are "present" in all channels. 

![baits_and_protein_level](https://user-images.githubusercontent.com/1895805/76375452-c8214580-633d-11ea-9634-f42a892b719f.png)

The black lines represent individual PSMs, the red line is the average of all PSMs as computed by ggplot2 and the blue line is quantitation on protein level by MSStatsTMT. 

Thus the ratios computed by proteinSummarization() are extremely suppressed compared to ratios I would get by simply finding the average of all peptides. 

Below is the data:

[example_data.zip](https://github.com/Vitek-Lab/MSstatsTMT/files/4315692/example_data.zip)

and code

```
 NSLComplex <- c("Q9H9L4" , "Q9P2N6", "Q9H7Z6")
PSMTable <- read.csv ("example_data.csv" , stringsAsFactors = F)

annotation.pd= data.frame (Run = rep ("NSL_tmt_unfr_6hours.raw", 16), 
                           Channel = c("126", "127N", "127C", "128N", "128C", "129N", "129C", "130N", "130C", "131N", "131C", "132N", "132C", "133N",  "133C",  "134N"), 
                           Condition = c(rep("control", 4),  rep("K2", 4), rep("K3", 4), rep("K8", 4)), 
                           Fraction = rep(1, 16), 
                           BioReplicate = "empty", Mixture = 1, TechRepMixture = 1, 
                           stringsAsFactors = FALSE)

PSMTMTStats <- PDtoMSstatsTMTFormat(PSMTable, annotation.pd,  rmPSM_withMissing_withinRun = TRUE)
protTMTStats <- proteinSummarization(PSMTMTStats, method="msstats", global_norm = FALSE)

PSMTMTStats <- rename (PSMTMTStats, "Protein" = "ProteinName", "Abundance" = "Intensity")
  
NSLComplexPSM <-  PSMTMTStats  %>% filter (Protein %in% NSLComplex) %>% group_by(Protein, PSM) %>% mutate (Abundance = Abundance/sum (Abundance)) 
NSLComplexProt <- protTMTStats %>% filter (Protein %in% NSLComplex) %>% group_by (Protein) %>% mutate (Abundance = Abundance/sum(Abundance))

NSLComplexPSM$Channel <- factor (NSLComplexPSM$Channel, levels = c("126", "127N", "127C", "128N", "128C", "129N", "129C", "130N", "130C", "131N", "131C", "132N", "132C", "133N",  "133C",  "134N"))
NSLComplexProt$Channel <- factor (NSLComplexProt$Channel, levels = c("126", "127N", "127C", "128N", "128C", "129N", "129C", "130N", "130C", "131N", "131C", "132N", "132C", "133N",  "133C",  "134N"))

ggplot (NSLComplexPSM, aes (Channel,  Abundance, group = PSM)) + geom_line () + 
  facet_wrap (~Protein) + 
  stat_summary(aes(y = Abundance), fun.y=mean, colour="red", geom="line",group=1, size = 1) + 
  theme(axis.text.x = element_text(angle = 90)) +
  geom_line(data=NSLComplexProt, aes(Channel, Abundance,group=1), color="blue")

```

**Comment by huang704** [comment]
hi, the peptide intensity from PDtoMSstatsTMTFormat() function is in original scale. But the protein intensity from proteinSummarization() is in log2 scale. Could you try again with the following code: 

ggplot (NSLComplexPSM, aes (Channel,  Abundance, group = PSM)) + geom_line () + 
  facet_wrap (~Protein) + 
  stat_summary(aes(y = Abundance), fun.y=mean, colour="red", geom="line",group=1, size = 1) + 
  theme(axis.text.x = element_text(angle = 90)) +
  geom_line(data=NSLComplexProt, aes(Channel, 2^Abundance,group=1), color="blue")

**Comment by pavel-shliaha** [comment]
Yes it works, thanks!
