### ISSUE TITLE
MSstatsTMT within the shiny tool with MQ data crashes 

### ISSUE THREAD

**Issue by yanademyanenko** [Vitek-Lab/MSstatsTMT#61]
Hi,

I've recently attended the MSstats workshop and have so far I've been using the desktop shiny tool analyse MSFragger output with MSstatsTMT.
However, MSFragger does not offer a function important for my analysis, whereas MQ does, so I would also like to process MQ data. 
I've been trying to upload my files, but the tool keeps crashing with the following error message:

Reached in evidence
Reached in proteins_group
Reached in maxq annot
Reached in get_data
File type is maxq 
Reached in maxq
Warning: Error in data.table::fread: File 'Protein.Accessions' does not exist or is non-readable. getwd()=='C:/Software/MSstats-Shiny-main/MSstats-Shiny-main'

I've changed the Protein ID field for Proteins, Leading.razor.protein, Gene.names etc. But the error is always the same. I've tried everything. As far as I understand, Protein.Accessions is a name of the column in msstats output generated by MSFragger (and also the converter tool?) Am I missing some libraries/tools to run this?

**Comment by devonjkohler** [comment]
Hi @yanademyanenko,

We have gone through alot of updates to MSstatsShiny since this was posted and this bug should be fixed. Please repost an issue here or on the google group if you still see this.
