### ISSUE TITLE
What is the 'raw.mq' file supposed to be?

### ISSUE THREAD

**Issue by pspealman** [Vitek-Lab/MSstatsTMT#62]
Hello,

I'd love to use this tool but I'm stuck on a very early step, building the annotation file for MaxQuant (v2.1.0.0) output. 
Following the 'annotation.mq' documentation in the manual, I see references to the 'raw.mq' file - but I'm at a loss to find any file by that name. 

Is it possible the file name has been changed since the documentation was written?

Pieter

**Comment by devonjkohler** [comment]
Hi @pspealman,

Sorry for the delayed response here. Wanted to respond in case anyone else has this issue. The `raw.mq` file is the "evidence" file in MaxQuant. This file contains the information on the PSM level.

Devon
