### ISSUE TITLE
contrast matrix definition

### ISSUE THREAD

**Issue by pavel-shliaha** [Vitek-Lab/MSstatsTMT#7]
the online tutorial describes contrast matrix:

contrast.matrix : Comparison between conditions of interests. 1) default is pairwise, which compare all possible pairs between two conditions. 2) Otherwise, users can specify the comparisons of interest. Based on the levels of conditions, specify 1 or -1 to the conditions of interests and 0 otherwise. The levels of conditions are sorted alphabetically.

I am not familiar with what contrast matrix is. is limma used for statistical tests and is contrast matrix functionality for limma?

**Comment by huang704** [comment]
In statistics, a contrast is a linear combination of conditions whose coefficients add up to zero, allowing comparison of different conditions. Many statistical tools, such as limma and MSstatsTMT, have functionality related to contrasts. For example, if there are four conditions (C1, C2, C3, C4) and you want to compare whether C1+C2 = C3+ C4, then you can specify a contrast (0.5, 0.5, -0.5, -0.5).
