### ISSUE TITLE
Some samples missing from output of protein summarization

### ISSUE THREAD

**Issue by Sandra-Murphy** [Vitek-Lab/MSstatsTMT#8]
Hello,

I've started to play around with MSstats TMT and just have a query about the output of proteinSummarization. I have 20 replicates so would expect 20 rows per protein (1 row for each replicate). This is the case for the majority of my proteins. However, in some cases I have less than 20 rows (abundance values per protein). For example, for one protein I have 17 rows of protein abundance corresponding to 17 samples. Some of the samples' abundance is listed as NA, whereas three of my samples just aren't listed at all for this particular protein.

What is the difference between a sample not being listed versus it having an NA abundance. I had assumed that if it was not listed, then that protein was simply missing in that sample.. But then what's the meaning of NA?

I have attached an example of two proteins from my output file, the first shows 20 abundance values for that particular protein, whilst the second protein only has 17 abundance values, some of which (those belonging to a 2nd TMT mixture) are NA.
[MSstats proteinSummarization example.xlsx](https://github.com/Vitek-Lab/MSstatsTMT/files/4662972/MSstats.proteinSummarization.example.xlsx)

Thanks for your help with this!

**Comment by huang704** [comment]
If a protein is missing from one sample, MSstatsTMT would put NA under the Abundance column. If the values are not listed, it may be because the channel is labeled as empty and MSstatsTMT will remove empty channels. Could you please also share the input to proteinSummarization() function if okay for you?

**Comment by Sandra-Murphy** [comment]
Thanks for getting back to me with this, I really appreciate it.

I don't have any empty columns as I used all channels in the TMTplex. I'm just curious as to why some are listed as NA and others not listed at all, as when I manually manipulate the output of proteinSummarization, anything that is missing appears as 0 (for all samples).

I've attached the input of proteinSummarization (input.maxquant) and the manipulated output using reshape2 (data).
[data.xlsx](https://github.com/Vitek-Lab/MSstatsTMT/files/4681556/data.xlsx)
[input.maxquant.zip](https://github.com/Vitek-Lab/MSstatsTMT/files/4681561/input.maxquant.zip)




Many thanks for your help!

**Comment by huang704** [comment]
Thank you for sharing this. I have run MSstatsTMT on your file and no NA abundances are listed in the output file. This is because MSstatsTMT removes the rows from the output of proteinSummarization() function if the abundance is NA. So you can think it is NA if the samples are not listed.

**Comment by Sandra-Murphy** [comment]
Thanks for having a look at it. When I do the analysis I still have the same issue of some proteins having NA values and some just not listed at all. I'll play around with it a bit more and see if I can get it to work.

Thanks for your help,
Sandra

**Comment by huang704** [comment]
Could you let me know the protein having NA values and some just not listed at all? I checked the output on my side and found no such protein. Or you can update MSstatsTMT to the latest versions and run the analysis again.

**Comment by Sandra-Murphy** [comment]
I tried updating the MSstatsTMT package and now it gives the following error "Error in `[.data.table`(raw, , require.col) : 
  j (the 2nd argument inside [...]) is a single symbol but column name 'require.col' is not found. Perhaps you intended DT[, ..require.col]. This difference to data.frame is deliberate and explained in FAQ 1.1." when using the function proteinSummarization, even though I am using the same code and files that worked before.

In the original analysis, the proteins with NA values were 
O15228
P49903;P49903-2;P49903-3
Q06136
Q5K651
Q6YP21-3;Q6YP21
Q71DI3
Q96B97;Q96B97-2
Q9BPX5
Q9H7D7-2;Q9H7D7
Q9NNW7-2;Q9NNW7;Q9NNW7-4;Q9NNW7-3

Many thanks,
Sandra

**Comment by huang704** [comment]
MSstatsTMT had a bug due to the update of a dependent package. I have fixed it yesterday and the updated MSstatsTMT should be available in Bioconductor tomorrow afternoon. I checked the output from the latest MSstatsTMT and all the proteins you listed have no NA. So the problem is already fixed in the previous update of MSstatsTMT.

**Comment by Sandra-Murphy** [comment]
Super, thank you so much for all your help! 👍

**Comment by Sandra-Murphy** [comment]
I re-analysed my data with MSstatsTMT 1.6.2 and now it works perfectly, thank you!
