### ISSUE TITLE
Question about TechRepMixture

### ISSUE THREAD

**Issue by jpfeuffer** [Vitek-Lab/MSstatsTMT#9]
Hi @huang704 

Is it possible to specify TechRepMixture across two or more Mixtures in a continuously increasing manner?

e.g.
<img width="419" alt="Bildschirmfoto 2020-06-24 um 13 09 23" src="https://user-images.githubusercontent.com/8102638/85545140-f50f1500-b61b-11ea-98f8-ae6a09bf6cbc.png">

Or would that imply a different design in comparison to a repeated/matching specification (1,2,3; 1,2,3; ...)?

**Comment by huang704** [comment]
Yes, you can specify the TechRepMixture column in an increasing manner across mixtures. It is the same as a repeated manner as long as the TechRepMixture column belonging to the same mixture has different values.

**Comment by jpfeuffer** [comment]
Great. Thank you, this is what I was hoping for.
